[package]
name = "voxmux-audio"
version = "0.1.0"
edition = "2021"

[dependencies]
voxmux-core = { workspace = true }
cpal = { workspace = true }
ringbuf = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
